Registar/Controllers/UsersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Registar.Models;
using System;
using System.Web.Mvc;


namespace Registar.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {


        
                // GET: Users
        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ViewBag.Name = user.Name;
                ViewBag.displayMenu = "No";

                if (isAdminUser())
                {
                    ViewBag.displayMenu = "Yes";
                }
                return View();
            }
            else
            {
                ViewBag.Name = "Not Logged IN";
            }
            return View();
        }



       


    }

}

Registar/Controllers/ZapisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Registar.DAL;
using Registar.Models;

namespace Registar.Controllers
{
    public class ZapisController : Controller
    {
        private RegistarContext db = new RegistarContext();

        private void PopulateOsobaDropDownList(object selectedO = null)
        {
            var oQuery = from d in db.Osoba
                         
                         select d;
            ViewBag.OsobaID = new SelectList(oQuery, "OsobaID", "Ime" +" ", "Prezime", selectedO);
        }

        private void PopulatePolicajacDropDownList(object selectedP = null)
        {
            var pQuery = from d in db.Policajac
                         //orderby db.Policajac
                         select d;
            ViewBag.PolicajacID = new SelectList(pQuery, "PolicajacID", "PolicajacIme", "PolicajacPrezime", selectedP);
        }

        private void PopulatePrekrsajDropDownList(object selectedR = null)
        {
            var rQuery = from d in db.Prekrsaj
                         //orderby db.Prekrsaj
                         select d;
            ViewBag.PrekrsajID = new SelectList(rQuery, "PrekrsajID", "OpisPrekrsaja", selectedR);
        }


        public ActionResult Index()
        {
            var zapis = db.Zapis.Include(c => c.OsobaID);
            var zapis2 = zapis.Include(c => c.PolicajacID);
            var zapis3 = zapis2.Include(c => c.PrekrsajID);
            return View(zapis3.ToList());
        }


        public ActionResult Details(int id)
        {
            Zapis zapis = db.Zapis.Find(id);
            PopulateOsobaDropDownList(zapis.OsobaID);
            PopulatePolicajacDropDownList(zapis.PolicajacID);
            PopulatePrekrsajDropDownList(zapis.PrekrsajID);
            if (zapis == null)
            {
                return HttpNotFound();
            }
            return View(zapis);
        }

      
        public ActionResult Create()
        {
            PopulateOsobaDropDownList();
            PopulatePolicajacDropDownList();
            PopulatePrekrsajDropDownList();
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ZapisID,Datum,OsobaID_OsobaID,PolicajacID_PolicajacID,PrekrsajID_PrekrsajID")] Zapis zapis)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Zapis.Add(zapis);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.)
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");

            }
            PopulateOsobaDropDownList(zapis.OsobaID);
            PopulatePolicajacDropDownList(zapis.PolicajacID);
            PopulatePrekrsajDropDownList(zapis.PrekrsajID);

            return View(zapis);
        }

        // GET: Zapis1/Edit/5
        public ActionResult Edit(int id)
        {
            Zapis zapis = db.Zapis.Find(id);
            PopulateOsobaDropDownList(zapis.OsobaID);
            PopulatePolicajacDropDownList(zapis.PolicajacID);
            PopulatePrekrsajDropDownList(zapis.PrekrsajID);
            return View(zapis);
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ZapisID,Datum,OsobaID_OsobaID,PolicajacID_PolicajacID,PrekrsajID_PrekrsajID")] Zapis zapis)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(zapis).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.)
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }
            PopulateOsobaDropDownList(zapis.OsobaID);
            PopulatePolicajacDropDownList(zapis.PolicajacID);
            PopulatePolicajacDropDownList(zapis.PrekrsajID);
            return View(zapis);
        }




        // GET: Zapis1/Delete/5
        public ActionResult Delete(int id)
        {
            Zapis zapis = db.Zapis.Find(id);
            if (zapis == null)
            {
                return HttpNotFound();
            }
            return View(zapis);
        }

     
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Zapis zapis = db.Zapis.Find(id);
            db.Zapis.Remove(zapis);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }


    
}

Registar/Views/Users/Index.cshtml
<style>

    .btn-default {
        color: #fff;
        background-color: #337ab7;
        border-color: #2e6da4;
    }

    .container {
        padding-right: 15px;
        /* padding-left: 15px; */
        margin-right: auto;
        margin-left: auto;
        padding-left: 0px;
    }
</style>
@model Registar.Models.IndexViewModel
@{
    ViewBag.Title = "Index";

}




@if (ViewBag.displayMenu == "Yes")
{
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Registar</title>


    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li style="font-size:18px; text-align:left">@Html.ActionLink("Registar", "Index", "Home") </li>

                    <li>@Html.ActionLink("Pocetna", "Index", "Home")</li>
                    <li>@Html.ActionLink("O nama", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Osoblje", "Index", "Policajacs")</li>
                    <li>@Html.ActionLink("Zapisnik", "Index", "Zapis")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <br />
    <h1>&emsp;Administracija sistema </h1>
    <br />
    <h4>
        &emsp;
        Pregled osoblja institucije: &emsp;&emsp;&emsp;&ensp;
        <a class="btn btn-default" href="/Policajacs"> Osoblje </a>
    </h4>

    <br />
    <h4>
        &emsp;
        Pregled počinjenih prekršaja: &emsp;&emsp;
        <a class="btn btn-default" href="/Zapis">Zapisnik </a>
    </h4>
    <br />
    <h4>
        &emsp;
        Kreiranje nove vrste korisnika: &emsp;&ensp;
        <a class="btn btn-default" href="/Role">Kreiraj</a>
    </h4>




}
else
{
    <h2>&emsp;  Dobrodošao <strong>@ViewBag.Name</strong>  </h2>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Registar</title>


    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li style="font-size:18px; text-align:left">@Html.ActionLink("Registar", "Index", "Home") </li>

                    <li>@Html.ActionLink("Pocetna", "Index", "Home")</li>
                    <li>@Html.ActionLink("O nama", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Osoblje", "Index", "Policajacs")</li>
                    <li>@Html.ActionLink("Zapisnik", "Index", "Zapis")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    
    <h1>&emsp; </h1>
    
    <h4>
        &emsp;
        Pregled osoblja institucije: &emsp;&emsp;&emsp;&ensp;
        <a class="btn btn-default" href="/Policajacs"> Osoblje </a>
    </h4>

    <br />
    <h4>
        &emsp;
        Pregled počinjenih prekršaja: &emsp;&emsp;
        <a class="btn btn-default" href="/Zapis">Zapisnik </a>
    </h4>
    <br />

}